binance:
  api_key:
  secret_key:
  file:
bittrex:
  api_key:
  secret_key:
yieldwatch:
  wallet:
  jwt:
  file:
settings:
  currencies:
    - USD
  rounding: 6
  token_names:
    BUNNY: Pancake Bunny
  hide_tokens:
    - DOGE
  include_tokens:
    NEXO: 42
