binance:
  api_key:
  secret_key:
  file:
bittrex:
  api_key:
  secret_key:
yieldwatch:
  wallet:
  jwt:
  file:
apeboard:
  wallet:
  wallets:
    - bsc
    - matic
  farms:
    - pancakeswapBsc
0xtracker:
  wallet:
  farms:
    - "0xA9C9D9Aed47320835c84090c62dC324FcF24f683"
settings:
  currencies:
    - USD
  rounding: 6
  token_names:
    BUNNY: Pancake Bunny
  hide_tokens:
    - DOGE
  include_tokens:
    exchange1:
      NEXO: 42
    exchange2:
      NEXO: 1337
